### ISSUE TITLE
Add Jenkins Configuration as Code compatibility

### ISSUE THREAD

**Issue by marcemv90** [jenkinsci/environment-dashboard-plugin#170]
Hello,

It seems this plugin is can't be configured using [Jenkins Configuration as Code](https://github.com/jenkinsci/configuration-as-code-plugin) plugin. It would be nice if you could add support for it, so it configuration could be written something like follows:

```yaml
dashboardBuilder:
  numberOfDays: "60"
``` 
or any other syntax you consider the best.

Please let me know if further information is needed.

Many thank in advance,

Regards.

**Comment by willwh** [comment]
Thanks for posting this. We would need to look over the following guide and start writing up some issues:  https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md 

I have very little time I can devote to the project currently, leaving this note for later :)
